name: node workflow

on:
    push:
        branches: [master]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.10.0
              uses: actions/setup-node@v1
              with:
                  node-version: 14.10.0
            - run: npm i
